name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR
        run: ./mvnw -B package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t kolokvij:latest .
